settings:
  log: slack

install:
  assertReturnCode: 0
  go:
  - [ apt install -y golang-go ]
       
go-graphql:
  assertReturnCode: 0
  assertStdoutContains: '"hello":"world"'
  hello-world: 
  - [ go run examples/hello-world/main.go ]
