tests:
    hello:
        assertStdoutContains: '"hello":"world"'
        input:
            - ""
software:
    go-graphql:
        execute: ["go", "run", "examples/hello-world/main.go", "[[tests]]"]
        install:
            - apt install -y golang-go
